// Generates data/users.yaml with bcrypt-hashed passwords.
// Re-running this script overwrites users.yaml — use only for first-time seeding.
import fs from 'node:fs';
import path from 'node:path';
import bcrypt from 'bcryptjs';

const password_admin = process.env.PASSWORD_ADMIN;
const password_offizier = process.env.PASSWORD_OFFIZIER;
const password_unteroffizier = process.env.PASSWORD_UNTEROFFIZIER;
const password_soldat = process.env.PASSWORD_SOLDAT;


const USERS = [
  { username: 'Admin', role: 'Admin',         password: password_admin || 'ZSO1234' },
  { username: 'Of',    role: 'Offizier',      password: password_offizier || 'ZSO1234' },
  { username: 'Uof',   role: 'Unteroffizier', password: password_unteroffizier || 'ZSO1234' },
  { username: 'AdZS',  role: 'Soldat',        password: password_soldat || 'ZSO1234' },
];

let yaml = '# Auto-generated by scripts/seed-users.js. Edit by hand or run `npm run hash <pw>` for a new bcrypt hash.\nusers:\n';

for (const u of USERS) {
  const hash = bcrypt.hashSync(u.password, 10);
  yaml += `  ${u.username}:\n    role: ${u.role}\n    passwordHash: "${hash}"\n`;
}

const out = path.resolve('data/users.yaml');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, yaml);
console.log(`Wrote ${out} with ${USERS.length} users.`);